name: Scheduled Stable Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 6,0" # Run at midnight UTC on Saturday and Sunday
  workflow_dispatch:

jobs:
  prepare_build:
    name: Prepare Build
    runs-on: ubuntu-latest
    outputs:
      build_ref: ${{ steps.set_outputs.outputs.build_ref }}
      release_tag: ${{ steps.set_outputs.outputs.release_tag }}
      release_body: ${{ steps.set_outputs.outputs.release_body }}
    steps:
      - name: Set build and release information
        id: set_outputs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Set repository and ref
          REPO="zed-industries/zed"
          REF="${{ github.event_name == 'push' && github.sha || 'main' }}"
          
          # Get commit info for the release body
          COMMIT=$(gh api repos/$REPO/commits/$REF --jq '{sha: .sha, message: .commit.message, html_url: .html_url}')
          SHA=$(echo $COMMIT | jq -r '.sha' | cut -c1-8)
          MSG=$(echo $COMMIT | jq -r '.message' | head -n 1)
          URL=$(echo $COMMIT | jq -r '.html_url')
          
          echo "Building stable release from $REPO#$SHA"
          echo "build_ref=$REF" >> $GITHUB_OUTPUT
          echo "release_tag=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT
          echo "release_body=Stable build from $REPO commit [$SHA]($URL): $MSG" >> $GITHUB_OUTPUT

  trigger_build:
    name: Build
    needs: prepare_build
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ needs.prepare_build.outputs.build_ref }}

  trigger_release:
    name: Release
    needs: [prepare_build, trigger_build]
    uses: ./.github/workflows/release.yml
    with:
      is_prerelease: false
      release_tag: ${{ needs.prepare_build.outputs.release_tag }}
      release_body: ${{ needs.prepare_build.outputs.release_body }}
    permissions:
      contents: write
